export const WeatherIconLegends = new Map<string, string>([
    ["clearsky", "Klarvær"],
    ["cloudy", "Skyet"],
    ["fog", "Tåke"],
    ["heavyrainshowersandthunder", "Kraftige regnbyger og torden"],
    ["heavysleet", "Kraftig sludd"],
    ["heavysleetandthunder", "Kraftig sludd og torden"],
    ["heavysleetshowers", "Kraftige sluddbyger"],
    ["heavysleetshowersandthunder", "Kraftige sluddbyger og torden"],
    ["heavysnow", "Kraftig snø"],
    ["heavysnowandthunder", "Kraftig snø og torden"],
    ["heavysnowshowers", "Kraftige snøbyger"],
    ["heavysnowshowersandthunder", "Kraftige snøbyger og torden"],
    ["lightrain", "Lett regn"],
    ["lightrainandthunder", "Lett regn og torden"],
    ["lightrainshowers", "Lette regnbyger"],
    ["lightrainshowersandthunder", "Lette regnbyger og torden"],
    ["lightsleet", "Lett sludd"],
    ["lightsleetandthunder", "Lett sludd og torden"],
    ["lightsleetshowers", "Lette sluddbyger"],
    ["lightsnow", "Lett snø"],
    ["lightsnowandthunder", "Lett snø og torden"],
    ["lightsnowshowers", "Lette snøbyger"],
    ["lightssleetshowersandthunder", "Lette sluddbyger og torden"],
    ["lightssnowshowersandthunder", "Lette snøbyger og torden"],
    ["partlycloudy", "Delvis skyet"],
    ["rain", "Regn"],
    ["rainandthunder", "Regn og torden"],
    ["rainshowers", "Regnbyger"],
    ["rainshowersandthunder", "Regnbyger og torden"],
    ["sleet", "Sludd"],
    ["sleetandthunder", "Sludd og torden"],
    ["sleetshowers", "Sluddbyger"],
    ["sleetshowersandthunder", "Sluddbyger og torden"],
    ["snow", "Snø"],
    ["snowandthunder", "Snø og torden"],
    ["snowshowers", "Snøbyger"],
    ["snowshowersandthunder", "Snøbyger og torden"]
]);